title: Grzegorz GrzÄ™da
email: grzegorz.grzeda@g2labs.pl
description: >-
  I write in embedded C, python and whatever you need :)
twitter_username: GrzegorzGrzeda
github_username:  grzegorz-grzeda

theme: minima

include:
 - _pages